version: '3'

services:
  user-management-api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - './:/app'
    ports:
      - '3000:3000'
    depends_on:
      - sqlite
    environment:
      - NODE_ENV=production
      - DB_NAME=/data/db.sqlite
      - APP_ENV=development # or production based on your environment
    command: npm start

  migrate-db:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - './:/app'
    depends_on:
      - sqlite
    environment:
      - NODE_ENV=production
      - DB_NAME=/data/db.sqlite
      - APP_ENV=development # or production based on your environment
    # command: npm run migrate:up

  sqlite:
    image: nouchka/sqlite3:latest
    volumes:
      - ./database:/var/lib/sqlite/data
    ports:
      - '5432:5432' # Optional, if needed
