name: Deploy to Cloud Run - Deploy Pull Request

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name
        id: extract_branch
        run: echo "branch_name=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '361.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: user-management-api-${{ env.branch_name }}
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/user-management-api-service:${{ env.branch_name }}
          region: us-central1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
